/**
 * Upgrade IDs - Centralized constants for upgrade identification
 * This ensures type safety and easier maintenance when upgrades change
 */

export const UPGRADE_IDS = {
  // Basic Automation
  AI_INTERN: 1,
  BASH_SCRIPT: 2,
  CRON_JOB: 3,
  JUNIOR_DEV: 4,
  SENIOR_DEV: 5,
  TECH_LEAD: 6,
  ARCHITECT: 7,
  JUNIOR_DEVOPS: 8,
  SENIOR_DEVOPS: 9,
  SRE: 10,
  PLATFORM_ENGINEER: 11,
  LAMBDA_FUNCTION: 12,
  EDGE_FUNCTION: 13,
  KUBERNETES_CLUSTER: 14,
  MICROSERVICES: 15,
  ML_MODEL: 16,
  NEURAL_NETWORK: 17,
  DEEP_LEARNING: 18,
  AGI: 19,

  // Click Upgrades
  L1_CACHE: 20,
  L2_CACHE: 21,
  REDIS_CACHE: 22,
  CDN: 23,
  CONNECTION_POOL: 24,
  LOAD_BALANCER: 25,
  DATABASE_INDEX: 26,
  QUERY_OPTIMIZER: 27,
  POSTGREST_TURBO: 28,
  GRAPHQL: 29,
  GRPC: 30,
  RLS_BYPASS: 31,
  POSTGRES_SUPERUSER: 32,
  DATABASE_SHARDING: 33,

  // Infrastructure
  VPS: 34,
  DEDICATED_SERVER: 35,
  DATA_CENTER: 36,
  CLOUD_REGION: 37,
  MULTI_CLOUD: 38,
  EDGE_COMPUTING: 39,
  QUANTUM_COMPUTER: 40,

  // Databases
  SQLITE: 41,
  MYSQL: 42,
  POSTGRESQL: 43,
  MONGODB: 44,
  ELASTICSEARCH: 45,
  CLICKHOUSE: 46,
  BIGQUERY: 47,
  SNOWFLAKE: 48,

  // Security
  SSL_CERTIFICATE: 49,
  FIREWALL: 50,
  WAF: 51,
  DDOS_PROTECTION: 52,
  ZERO_TRUST: 53,
  HSM: 54,
  QUANTUM_ENCRYPTION: 55,

  // Monitoring
  LOGS: 56,
  METRICS: 57,
  ALERTING: 58,
  APM: 59,
  DISTRIBUTED_TRACING: 60,
  OBSERVABILITY: 61,
  AIOPS: 62,

  // Frontend
  HTML_CSS: 63,
  JAVASCRIPT: 64,
  REACT: 65,
  NEXTJS: 66,
  TYPESCRIPT: 67,
  WEBPACK: 68,
  VITE: 69,
  MICRO_FRONTENDS: 70,

  // Backend
  NODEJS: 71,
  EXPRESSJS: 72,
  FASTAPI: 73,
  GO_FIBER: 74,
  RUST_ACTIX: 75,
  SERVERLESS_FUNCTIONS: 76,
  EVENT_DRIVEN_ARCHITECTURE: 77,

  // Mobile
  REACT_NATIVE: 78,
  FLUTTER: 79,
  SWIFT_KOTLIN: 80,
  PWA: 81,
  AR_VR: 82,
  IOT_INTEGRATION: 83,

  // Testing
  UNIT_TESTS: 84,
  INTEGRATION_TESTS: 85,
  E2E_TESTS: 86,
  LOAD_TESTING: 87,
  CHAOS_ENGINEERING: 88,
  AI_TESTING: 89,

  // Analytics
  GOOGLE_ANALYTICS: 90,
  MIXPANEL: 91,
  AMPLITUDE: 92,
  DATA_PIPELINE: 93,
  REALTIME_ANALYTICS: 94,
  PREDICTIVE_ANALYTICS: 95,

  // Blockchain & Future
  SMART_CONTRACTS: 96,
  DEFI_PROTOCOL: 97,
  NFT_MARKETPLACE: 98,
  METAVERSE: 99,
  BRAIN_COMPUTER_INTERFACE: 100,
} as const;

/**
 * Upgrade Groups - Logical grouping of related upgrades
 */
export const UPGRADE_GROUPS = {
  AI_ML: [
    UPGRADE_IDS.AI_INTERN,
    UPGRADE_IDS.ML_MODEL,
    UPGRADE_IDS.NEURAL_NETWORK,
    UPGRADE_IDS.DEEP_LEARNING,
    UPGRADE_IDS.AGI,
    UPGRADE_IDS.AIOPS,
    UPGRADE_IDS.AI_TESTING,
    UPGRADE_IDS.BRAIN_COMPUTER_INTERFACE,
  ],
  DEVOPS: [
    UPGRADE_IDS.JUNIOR_DEVOPS,
    UPGRADE_IDS.SENIOR_DEVOPS,
    UPGRADE_IDS.SRE,
    UPGRADE_IDS.PLATFORM_ENGINEER,
  ],
  CLOUD: [
    UPGRADE_IDS.CLOUD_REGION,
    UPGRADE_IDS.MULTI_CLOUD,
    UPGRADE_IDS.EDGE_COMPUTING,
  ],
} as const;

/**
 * Helper type for upgrade IDs
 */
export type UpgradeId = typeof UPGRADE_IDS[keyof typeof UPGRADE_IDS];
