import { Upgrade } from "@/type/game";
import { getPrestigePriceMultiplier } from "./prestige";

const UPGRADES_DATA: Upgrade[] = [
  {
    id: 1,
    name: "AI Intern",
    description: "An intern who clicks for you",
    baseCost: 15,
    costGrowth: 1.15,
    ppsGain: 0.1,
    clickMultiplier: 0,
    category: "auto",
  },
  {
    id: 2,
    name: "Bash Script",
    description: "A simple script that automates",
    baseCost: 25,
    costGrowth: 1.15,
    ppsGain: 0.2,
    clickMultiplier: 0,
    category: "auto",
  },
  {
    id: 3,
    name: "Cron Job",
    description: "Scheduled execution",
    baseCost: 50,
    costGrowth: 1.15,
    ppsGain: 0.5,
    clickMultiplier: 0,
    category: "auto",
  },
  {
    id: 4,
    name: "Junior Dev",
    description: "A dev who automates your clicks",
    baseCost: 100,
    costGrowth: 1.15,
    ppsGain: 1,
    clickMultiplier: 0,
    category: "auto",
  },
  {
    id: 5,
    name: "Senior Dev",
    description: "Experience and efficiency",
    baseCost: 200,
    costGrowth: 1.15,
    ppsGain: 2,
    clickMultiplier: 0,
    category: "auto",
  },
  {
    id: 6,
    name: "Tech Lead",
    description: "Leads a team of devs",
    baseCost: 400,
    costGrowth: 1.15,
    ppsGain: 4,
    clickMultiplier: 0,
    category: "auto",
  },
  {
    id: 7,
    name: "Architect",
    description: "Designs complex systems",
    baseCost: 800,
    costGrowth: 1.15,
    ppsGain: 8,
    clickMultiplier: 0,
    category: "auto",
  },
  {
    id: 8,
    name: "Junior DevOps",
    description: "Automates deployment",
    baseCost: 1100,
    costGrowth: 1.15,
    ppsGain: 12,
    clickMultiplier: 0,
    category: "auto",
  },
  {
    id: 9,
    name: "Senior DevOps",
    description: "Optimizes your pipeline",
    baseCost: 2000,
    costGrowth: 1.15,
    ppsGain: 20,
    clickMultiplier: 0,
    category: "auto",
  },
  {
    id: 10,
    name: "SRE",
    description: "Site Reliability Engineer",
    baseCost: 3500,
    costGrowth: 1.15,
    ppsGain: 35,
    clickMultiplier: 0,
    category: "auto",
  },
  {
    id: 11,
    name: "Platform Engineer",
    description: "Builds infrastructure",
    baseCost: 6000,
    costGrowth: 1.15,
    ppsGain: 60,
    clickMultiplier: 0,
    category: "auto",
  },
  {
    id: 12,
    name: "Lambda Function",
    description: "Serverless computing",
    baseCost: 12000,
    costGrowth: 1.15,
    ppsGain: 100,
    clickMultiplier: 0,
    category: "auto",
  },
  {
    id: 13,
    name: "Edge Function",
    description: "Globally distributed clicks",
    baseCost: 20000,
    costGrowth: 1.15,
    ppsGain: 180,
    clickMultiplier: 0,
    category: "auto",
  },
  {
    id: 14,
    name: "Kubernetes Cluster",
    description: "Container orchestration",
    baseCost: 35000,
    costGrowth: 1.15,
    ppsGain: 300,
    clickMultiplier: 0,
    category: "auto",
  },
  {
    id: 15,
    name: "Microservices",
    description: "Distributed architecture",
    baseCost: 60000,
    costGrowth: 1.15,
    ppsGain: 500,
    clickMultiplier: 0,
    category: "auto",
  },
  {
    id: 16,
    name: "ML Model",
    description: "Artificial intelligence",
    baseCost: 100000,
    costGrowth: 1.15,
    ppsGain: 800,
    clickMultiplier: 0,
    category: "auto",
  },
  {
    id: 17,
    name: "Neural Network",
    description: "Neural network",
    baseCost: 180000,
    costGrowth: 1.15,
    ppsGain: 700,
    clickMultiplier: 0,
    category: "auto",
  },
  {
    id: 18,
    name: "Deep Learning",
    description: "Deep learning",
    baseCost: 300000,
    costGrowth: 1.15,
    ppsGain: 1000,
    clickMultiplier: 0,
    category: "auto",
  },
  // {
  //   id: 19,
  //   name: "AGI",
  //   description: "Artificial General Intelligence",
  //   baseCost: 500000,
  //   costGrowth: 1.15,
  //   ppsGain: 1500,
  //   clickMultiplier: 0,
  //   category: "auto",
  // },
  {
    id: 20,
    name: "L1 Cache",
    description: "Processor cache",
    baseCost: 50,
    costGrowth: 1.2,
    ppsGain: 0,
    clickMultiplier: 0.5,
    category: "click",
  },
  {
    id: 21,
    name: "L2 Cache",
    description: "Larger cache",
    baseCost: 100,
    costGrowth: 1.2,
    ppsGain: 0,
    clickMultiplier: 1,
    category: "click"
  },
  {
    id: 22,
    name: "Redis Cache",
    description: "In-memory cache",
    baseCost: 200,
    costGrowth: 1.2,
    ppsGain: 0,
    clickMultiplier: 2,
    category: "click",
  },
  {
    id: 23,
    name: "CDN",
    description: "Content Delivery Network",
    baseCost: 400,
    costGrowth: 1.2,
    ppsGain: 0,
    clickMultiplier: 3,
    category: "click",
  },
  {
    id: 24,
    name: "Connection Pool",
    description: "Optimizes connections",
    baseCost: 1000,
    costGrowth: 1.2,
    ppsGain: 0,
    clickMultiplier: 5,
    category: "click",
  },
  {
    id: 25,
    name: "Load Balancer",
    description: "Distributes load",
    baseCost: 2000,
    costGrowth: 1.2,
    ppsGain: 0,
    clickMultiplier: 8,
    category: "click",
  },
  {
    id: 26,
    name: "Database Index",
    description: "Speeds up queries",
    baseCost: 4000,
    costGrowth: 1.2,
    ppsGain: 0,
    clickMultiplier: 12,
    category: "click",
  },
  {
    id: 27,
    name: "Query Optimizer",
    description: "Optimizes automatically",
    baseCost: 8000,
    costGrowth: 1.2,
    ppsGain: 0,
    clickMultiplier: 20,
    category: "click",
  },
  {
    id: 28,
    name: "PostgREST Turbo",
    description: "Ultra-fast API",
    baseCost: 15000,
    costGrowth: 1.2,
    ppsGain: 0,
    clickMultiplier: 30,
    category: "click",
  },
  {
    id: 29,
    name: "GraphQL",
    description: "Optimized queries",
    baseCost: 25000,
    costGrowth: 1.2,
    ppsGain: 0,
    clickMultiplier: 50,
    category: "click",
  },
  {
    id: 30,
    name: "gRPC",
    description: "High performance communication",
    baseCost: 40000,
    costGrowth: 1.2,
    ppsGain: 0,
    clickMultiplier: 80,
    category: "click",
  },
  {
    id: 31,
    name: "RLS Bypass",
    description: "Bypasses policies",
    baseCost: 75000,
    costGrowth: 1.2,
    ppsGain: 0,
    clickMultiplier: 120,
    category: "click",
  },
  {
    id: 32,
    name: "Postgres Superuser",
    description: "Full root access",
    baseCost: 150000,
    costGrowth: 1.2,
    ppsGain: 0,
    clickMultiplier: 200,
    category: "click",
  },
  {
    id: 33,
    name: "Database Sharding",
    description: "Horizontal distribution",
    baseCost: 300000,
    costGrowth: 1.2,
    ppsGain: 0,
    clickMultiplier: 350,
    category: "click",
  },
  {
    id: 34,
    name: "VPS",
    description: "Virtual private server",
    baseCost: 500,
    costGrowth: 1.18,
    ppsGain: 3,
    clickMultiplier: 0,
    category: "infra",
  },
  {
    id: 35,
    name: "Dedicated Server",
    description: "Dedicated server",
    baseCost: 1500,
    costGrowth: 1.18,
    ppsGain: 10,
    clickMultiplier: 0,
    category: "infra",
  },
  {
    id: 36,
    name: "Data Center",
    description: "Data center",
    baseCost: 5000,
    costGrowth: 1.18,
    ppsGain: 35,
    clickMultiplier: 0,
    category: "infra",
  },
  {
    id: 37,
    name: "Cloud Region",
    description: "Complete cloud region",
    baseCost: 15000,
    costGrowth: 1.18,
    ppsGain: 100,
    clickMultiplier: 0,
    category: "infra",
  },
  {
    id: 38,
    name: "Multi-Cloud",
    description: "Multiple cloud providers",
    baseCost: 50000,
    costGrowth: 1.18,
    ppsGain: 300,
    clickMultiplier: 0,
    category: "infra",
  },
  {
    id: 39,
    name: "Edge Computing",
    description: "Edge computing",
    baseCost: 100000,
    costGrowth: 1.18,
    ppsGain: 600,
    clickMultiplier: 0,
    category: "infra",
  },
  {
    id: 40,
    name: "Quantum Computer",
    description: "Quantum computer",
    baseCost: 500000,
    costGrowth: 1.18,
    ppsGain: 3000,
    clickMultiplier: 0,
    category: "infra",
  },
  {
    id: 41,
    name: "SQLite",
    description: "Lightweight database",
    baseCost: 300,
    costGrowth: 1.16,
    ppsGain: 1.5,
    clickMultiplier: 0,
    category: "database",
  },
  {
    id: 42,
    name: "MySQL",
    description: "Relational database",
    baseCost: 800,
    costGrowth: 1.16,
    ppsGain: 4,
    clickMultiplier: 0,
    category: "database",
  },
  {
    id: 43,
    name: "PostgreSQL",
    description: "Advanced database",
    baseCost: 2000,
    costGrowth: 1.16,
    ppsGain: 12,
    clickMultiplier: 0,
    category: "database",
  },
  {
    id: 44,
    name: "MongoDB",
    description: "NoSQL database",
    baseCost: 5000,
    costGrowth: 1.16,
    ppsGain: 30,
    clickMultiplier: 0,
    category: "database",
  },
  {
    id: 45,
    name: "Elasticsearch",
    description: "Search engine",
    baseCost: 12000,
    costGrowth: 1.16,
    ppsGain: 80,
    clickMultiplier: 0,
    category: "database",
  },
  {
    id: 46,
    name: "ClickHouse",
    description: "Analytics database",
    baseCost: 25000,
    costGrowth: 1.16,
    ppsGain: 180,
    clickMultiplier: 0,
    category: "database",
  },
  {
    id: 47,
    name: "BigQuery",
    description: "Data warehouse",
    baseCost: 60000,
    costGrowth: 1.16,
    ppsGain: 400,
    clickMultiplier: 0,
    category: "database",
  },
  {
    id: 48,
    name: "Snowflake",
    description: "Cloud data platform",
    baseCost: 150000,
    costGrowth: 1.16,
    ppsGain: 1000,
    clickMultiplier: 0,
    category: "database",
  },
  {
    id: 49,
    name: "SSL Certificate",
    description: "HTTPS encryption",
    baseCost: 100,
    costGrowth: 1.25,
    ppsGain: 0,
    clickMultiplier: 1,
    category: "security",
  },
  {
    id: 50,
    name: "Firewall",
    description: "Network protection",
    baseCost: 500,
    costGrowth: 1.25,
    ppsGain: 2,
    clickMultiplier: 0,
    category: "security",
  },
  {
    id: 51,
    name: "WAF",
    description: "Web Application Firewall",
    baseCost: 2000,
    costGrowth: 1.25,
    ppsGain: 8,
    clickMultiplier: 0,
    category: "security",
  },
  {
    id: 52,
    name: "DDoS Protection",
    description: "Attack protection",
    baseCost: 8000,
    costGrowth: 1.25,
    ppsGain: 35,
    clickMultiplier: 0,
    category: "security",
  },
  {
    id: 53,
    name: "Zero Trust",
    description: "Security architecture",
    baseCost: 30000,
    costGrowth: 1.25,
    ppsGain: 150,
    clickMultiplier: 0,
    category: "security",
  },
  {
    id: 54,
    name: "HSM",
    description: "Hardware Security Module",
    baseCost: 100000,
    costGrowth: 1.25,
    ppsGain: 500,
    clickMultiplier: 0,
    category: "security",
  },
  {
    id: 55,
    name: "Quantum Encryption",
    description: "Quantum encryption",
    baseCost: 500000,
    costGrowth: 1.25,
    ppsGain: 2500,
    clickMultiplier: 0,
    category: "security",
  },
  {
    id: 56,
    name: "Logs",
    description: "Basic logging",
    baseCost: 200,
    costGrowth: 1.2,
    ppsGain: 0.8,
    clickMultiplier: 0,
    category: "monitoring",
  },
  {
    id: 57,
    name: "Metrics",
    description: "System metrics",
    baseCost: 600,
    costGrowth: 1.2,
    ppsGain: 3,
    clickMultiplier: 0,
    category: "monitoring",
  },
  {
    id: 58,
    name: "Alerting",
    description: "Alert system",
    baseCost: 1500,
    costGrowth: 1.2,
    ppsGain: 8,
    clickMultiplier: 0,
    category: "monitoring",
  },
  {
    id: 59,
    name: "APM",
    description: "Application Performance Monitoring",
    baseCost: 4000,
    costGrowth: 1.2,
    ppsGain: 22,
    clickMultiplier: 0,
    category: "monitoring",
  },
  {
    id: 60,
    name: "Distributed Tracing",
    description: "Distributed tracing",
    baseCost: 12000,
    costGrowth: 1.2,
    ppsGain: 65,
    clickMultiplier: 0,
    category: "monitoring",
  },
  {
    id: 61,
    name: "Observability",
    description: "Complete observability",
    baseCost: 35000,
    costGrowth: 1.2,
    ppsGain: 200,
    clickMultiplier: 0,
    category: "monitoring",
  },
  {
    id: 62,
    name: "AIOps",
    description: "AI for operations",
    baseCost: 100000,
    costGrowth: 1.2,
    ppsGain: 600,
    clickMultiplier: 0,
    category: "monitoring",
  },
  {
    id: 63,
    name: "HTML/CSS",
    description: "Basic technologies",
    baseCost: 50,
    costGrowth: 1.15,
    ppsGain: 0.3,
    clickMultiplier: 0,
    category: "frontend",
  },
  {
    id: 64,
    name: "JavaScript",
    description: "Dynamic language",
    baseCost: 150,
    costGrowth: 1.15,
    ppsGain: 1,
    clickMultiplier: 0,
    category: "frontend",
  },
  {
    id: 65,
    name: "React",
    description: "UI library",
    baseCost: 500,
    costGrowth: 1.15,
    ppsGain: 3,
    clickMultiplier: 0,
    category: "frontend",
  },
  {
    id: 66,
    name: "Next.js",
    description: "React framework",
    baseCost: 1500,
    costGrowth: 1.15,
    ppsGain: 10,
    clickMultiplier: 0,
    category: "frontend",
  },
  {
    id: 67,
    name: "TypeScript",
    description: "Typed JavaScript",
    baseCost: 4000,
    costGrowth: 1.15,
    ppsGain: 25,
    clickMultiplier: 0,
    category: "frontend",
  },
  {
    id: 68,
    name: "Webpack",
    description: "Module bundler",
    baseCost: 10000,
    costGrowth: 1.15,
    ppsGain: 65,
    clickMultiplier: 0,
    category: "frontend",
  },
  {
    id: 69,
    name: "Vite",
    description: "Fast build tool",
    baseCost: 25000,
    costGrowth: 1.15,
    ppsGain: 180,
    clickMultiplier: 0,
    category: "frontend",
  },
  {
    id: 70,
    name: "Micro-frontends",
    description: "Modular architecture",
    baseCost: 75000,
    costGrowth: 1.15,
    ppsGain: 500,
    clickMultiplier: 0,
    category: "frontend",
  },
  {
    id: 71,
    name: "Node.js",
    description: "JavaScript runtime",
    baseCost: 300,
    costGrowth: 1.17,
    ppsGain: 1.5,
    clickMultiplier: 0,
    category: "backend",
  },
  {
    id: 72,
    name: "Express.js",
    description: "Web framework",
    baseCost: 800,
    costGrowth: 1.17,
    ppsGain: 4.5,
    clickMultiplier: 0,
    category: "backend",
  },
  {
    id: 73,
    name: "FastAPI",
    description: "Fast Python API",
    baseCost: 2000,
    costGrowth: 1.17,
    ppsGain: 12,
    clickMultiplier: 0,
    category: "backend",
  },
  {
    id: 74,
    name: "Go Fiber",
    description: "Performant Go framework",
    baseCost: 5000,
    costGrowth: 1.17,
    ppsGain: 35,
    clickMultiplier: 0,
    category: "backend",
  },
  {
    id: 75,
    name: "Rust Actix",
    description: "Ultra-fast Rust framework",
    baseCost: 15000,
    costGrowth: 1.17,
    ppsGain: 100,
    clickMultiplier: 0,
    category: "backend",
  },
  {
    id: 76,
    name: "Serverless Functions",
    description: "Serverless computing",
    baseCost: 40000,
    costGrowth: 1.17,
    ppsGain: 280,
    clickMultiplier: 0,
    category: "backend",
  },
  {
    id: 77,
    name: "Event-Driven Architecture",
    description: "Event-driven architecture",
    baseCost: 100000,
    costGrowth: 1.17,
    ppsGain: 700,
    clickMultiplier: 0,
    category: "backend",
  },
  {
    id: 78,
    name: "React Native",
    description: "Cross-platform mobile apps",
    baseCost: 1000,
    costGrowth: 1.2,
    ppsGain: 5,
    clickMultiplier: 0,
    category: "mobile",
  },
  {
    id: 79,
    name: "Flutter",
    description: "Google mobile framework",
    baseCost: 3000,
    costGrowth: 1.2,
    ppsGain: 18,
    clickMultiplier: 0,
    category: "mobile",
  },
  {
    id: 80,
    name: "Swift/Kotlin",
    description: "Native development",
    baseCost: 8000,
    costGrowth: 1.2,
    ppsGain: 50,
    clickMultiplier: 0,
    category: "mobile",
  },
  {
    id: 81,
    name: "PWA",
    description: "Progressive Web App",
    baseCost: 20000,
    costGrowth: 1.2,
    ppsGain: 140,
    clickMultiplier: 0,
    category: "mobile",
  },
  {
    id: 82,
    name: "AR/VR",
    description: "Augmented/Virtual Reality",
    baseCost: 60000,
    costGrowth: 1.2,
    ppsGain: 400,
    clickMultiplier: 0,
    category: "mobile",
  },
  {
    id: 83,
    name: "IoT Integration",
    description: "Internet of Things",
    baseCost: 150000,
    costGrowth: 1.2,
    ppsGain: 1000,
    clickMultiplier: 0,
    category: "mobile",
  },
  {
    id: 84,
    name: "Unit Tests",
    description: "Unit tests",
    baseCost: 400,
    costGrowth: 1.15,
    ppsGain: 2,
    clickMultiplier: 0,
    category: "testing",
  },
  {
    id: 85,
    name: "Integration Tests",
    description: "Integration tests",
    baseCost: 1200,
    costGrowth: 1.15,
    ppsGain: 7,
    clickMultiplier: 0,
    category: "testing",
  },
  {
    id: 86,
    name: "E2E Tests",
    description: "End-to-end tests",
    baseCost: 3500,
    costGrowth: 1.15,
    ppsGain: 22,
    clickMultiplier: 0,
    category: "testing",
  },
  {
    id: 87,
    name: "Load Testing",
    description: "Load testing",
    baseCost: 10000,
    costGrowth: 1.15,
    ppsGain: 70,
    clickMultiplier: 0,
    category: "testing",
  },
  {
    id: 88,
    name: "Chaos Engineering",
    description: "Resilience testing",
    baseCost: 30000,
    costGrowth: 1.15,
    ppsGain: 200,
    clickMultiplier: 0,
    category: "testing",
  },
  {
    id: 89,
    name: "AI Testing",
    description: "AI-automated testing",
    baseCost: 100000,
    costGrowth: 1.15,
    ppsGain: 700,
    clickMultiplier: 0,
    category: "testing",
  },
  {
    id: 90,
    name: "Google Analytics",
    description: "Basic web analytics",
    baseCost: 100,
    costGrowth: 1.18,
    ppsGain: 0.5,
    clickMultiplier: 0,
    category: "analytics",
  },
  {
    id: 91,
    name: "Mixpanel",
    description: "Product analytics",
    baseCost: 800,
    costGrowth: 1.18,
    ppsGain: 4,
    clickMultiplier: 0,
    category: "analytics",
  },
  {
    id: 92,
    name: "Amplitude",
    description: "Behavioral analytics",
    baseCost: 3000,
    costGrowth: 1.18,
    ppsGain: 18,
    clickMultiplier: 0,
    category: "analytics",
  },
  {
    id: 93,
    name: "Data Pipeline",
    description: "Data pipeline",
    baseCost: 12000,
    costGrowth: 1.18,
    ppsGain: 80,
    clickMultiplier: 0,
    category: "analytics",
  },
  {
    id: 94,
    name: "Real-time Analytics",
    description: "Real-time analytics",
    baseCost: 40000,
    costGrowth: 1.18,
    ppsGain: 280,
    clickMultiplier: 0,
    category: "analytics",
  },
  {
    id: 95,
    name: "Predictive Analytics",
    description: "Predictive analytics",
    baseCost: 120000,
    costGrowth: 1.18,
    ppsGain: 850,
    clickMultiplier: 0,
    category: "analytics",
  },
  {
    id: 96,
    name: "Smart Contracts",
    description: "Smart contracts",
    baseCost: 25000,
    costGrowth: 1.3,
    ppsGain: 150,
    clickMultiplier: 0,
    category: "blockchain",
  },
  {
    id: 97,
    name: "DeFi Protocol",
    description: "Decentralized finance",
    baseCost: 80000,
    costGrowth: 1.3,
    ppsGain: 500,
    clickMultiplier: 0,
    category: "blockchain",
  },
  {
    id: 98,
    name: "NFT Marketplace",
    description: "Non-fungible tokens marketplace",
    baseCost: 200000,
    costGrowth: 1.3,
    ppsGain: 1200,
    clickMultiplier: 0,
    category: "blockchain",
  },
  {
    id: 99,
    name: "Metaverse",
    description: "Virtual universe",
    baseCost: 500000,
    costGrowth: 1.4,
    ppsGain: 1200,
    clickMultiplier: 0,
    category: "future",
  },
  {
    id: 100,
    name: "Brain-Computer Interface",
    description: "Brain-computer interface",
    baseCost: 1000000,
    costGrowth: 1.4,
    ppsGain: 2000,
    clickMultiplier: 0,
    category: "future",
  }
]

export const getUpgradeById = (id: number): Upgrade | undefined => {
  return UPGRADES_DATA.find(upgrade => upgrade.id === id);
}

export const getUnlockThreshold = (upgradeIndex: number) => {
  const thresholds = [0, 10, 50, 100, 250, 500, 1000, 2000, 5000, 10000, 25000, 50000];
  return thresholds[upgradeIndex] || thresholds[thresholds.length - 1] * Math.pow(2, upgradeIndex - thresholds.length + 1);
};

export const getUpgradeCost = (upgrade: Upgrade, currentLevel: number = 0, prestigeLevel: number = 0): number => {
  const baseCost = upgrade.baseCost * Math.pow(upgrade.costGrowth, currentLevel);
  const prestigeMultiplier = getPrestigePriceMultiplier(prestigeLevel);
  return Math.floor(baseCost * prestigeMultiplier);
};

// New function to get scaled PPS gain
export const getUpgradePPSGain = (upgrade: Upgrade, prestigeLevel: number = 0): number => {
  const prestigeMultiplier = Math.max(1, Math.pow(1.5, prestigeLevel));
  return upgrade.ppsGain * prestigeMultiplier;
};

// New function to get scaled click multiplier
export const getUpgradeClickMultiplier = (upgrade: Upgrade, prestigeLevel: number = 0): number => {
  const prestigeMultiplier = Math.max(1, Math.pow(1.5, prestigeLevel));
  return upgrade.clickMultiplier * prestigeMultiplier;
};

export const getRequiredTotalForNext = (currentTotalPower: number): number | null => {
  const allUpgrades = getAllUpgrades();
  
  const nextUpgradeIndex = allUpgrades.findIndex((_, index) => {
    const threshold = getUnlockThreshold(index);
    return currentTotalPower < threshold;
  });
  
  if (nextUpgradeIndex === -1) return null;
  return getUnlockThreshold(nextUpgradeIndex);
}

export const getAllUpgrades = (): Upgrade[] => {
  return UPGRADES_DATA;
}

export const getFirstLockedUpgradeIndex = (totalPower: number): number => {
  const allUpgrades = getAllUpgrades();
  return allUpgrades.findIndex((_, index) => totalPower < getUnlockThreshold(index));
};